############################################
# Smoke Test
############################################

SMOKE=FACEBOOK,INSTAGRAM,GOOGLE
ISOLATION=LINKEDIN,GITHUB,GOOGLE
MIXED=FACEBOOK,INSTAGRAM,GOOGLE,LINKEDIN,GITHUB


############################################
# Facebook
############################################

FACEBOOK_SCRIPT=Scripts/TestScripts/Facebook.jmx
FACEBOOK_USERS=10
FACEBOOK_DURATION=300
FACEBOOK_RAMPUP=30
FACEBOOK_LOOPS=1
FACEBOOK_ENV=PERF

############################################
# Instagram
############################################

INSTAGRAM_SCRIPT=Scripts/TestScripts/instagram.jmx
INSTAGRAM_USERS=10
INSTAGRAM_DURATION=5
INSTAGRAM_RAMPUP=30
INSTAGRAM_LOOPS=1
INSTAGRAM_ENV=PERF


############################################
# Google
############################################

GOOGLE_SCRIPT=Scripts/TestScripts/Google.jmx
GOOGLE_USERS=10
GOOGLE_DURATION=5
GOOGLE_RAMPUP=30
GOOGLE_LOOPS=1
GOOGLE_ENV=PERF

############################################
# LinkedIn
############################################

LINKEDIN_SCRIPT=Scripts/TestScripts/Linkedin.jmx
LINKEDIN_USERS=10
LINKEDIN_DURATION=5
LINKEDIN_RAMPUP=30
LINKEDIN_LOOPS=1
LINKEDIN_ENV=PERF

############################################
# GitHub
############################################

GITHUB_SCRIPT=Scripts/TestScripts/GitHub.jmx
GITHUB_USERS=10
GITHUB_DURATION=5
GITHUB_RAMPUP=30
GITHUB_LOOPS=1
GITHUB_ENV=PERF