############################################
# Smoke Test
############################################

SMOKE=FACEBOOK,INSTAGRAM,GOOGLE
ISOLATION=LinkedIn,GitHub,GOOGLE
MIXED==FACEBOOK,INSTAGRAM,GOOGLE,LinkedIn,GitHub


############################################
# Facebook
############################################

FACEBOOK_SCRIPT=Scripts/TestScripts/Facebook.jmx
FACEBOOK_DURATION=5
FACEBOOK_USERS=10

############################################
# Instagram
############################################

INSTAGRAM_SCRIPT=Scripts/TestScripts/instagram.jmx
INSTAGRAM_DURATION=5
INSTAGRAM_USERS=10

############################################
# Google
############################################

GOOGLE_SCRIPT=Scripts/TestScripts/Google.jmx
GOOGLE_DURATION=5
GOOGLE_USERS=10

############################################
# LinkedIn
############################################

LINKEDIN_SCRIPT=Scripts/TestScripts/Linkedin.jmx
LINKEDIN_DURATION=5
LINKEDIN_USERS=10

############################################
# GitHub
############################################

GITHUB_SCRIPT=Scripts/TestScripts/GitHub.jmx
GITHUB_DURATION=5
GITHUB_USERS=10