############################################
# Smoke Test
############################################

SMOKE=FACEBOOK,INSTAGRAM,GOOGLE
ISOLATION=LINKEDIN,GITHUB,GOOGLE
MIXED=FACEBOOK,INSTAGRAM,GOOGLE,LINKEDIN,GITHUB


############################################
# Facebook
############################################

FACEBOOK_SCRIPT=Scripts/TestScripts/Facebook.jmx
FACEBOOK_USERS=10
FACEBOOK_DURATION=30
FACEBOOK_RAMPUP=2
FACEBOOK_LOOPS=5
FACEBOOK_ENV=PERF

############################################
# Instagram
############################################

INSTAGRAM_SCRIPT=Scripts/TestScripts/instagram.jmx
INSTAGRAM_USERS=10
INSTAGRAM_DURATION=30
INSTAGRAM_RAMPUP=2
INSTAGRAM_LOOPS=5
INSTAGRAM_ENV=PERF


############################################
# Google
############################################

GOOGLE_SCRIPT=Scripts/TestScripts/Google.jmx
GOOGLE_USERS=10
GOOGLE_DURATION=30
GOOGLE_RAMPUP=3
GOOGLE_LOOPS=5
GOOGLE_ENV=PERF

############################################
# LinkedIn
############################################

LINKEDIN_SCRIPT=Scripts/TestScripts/Linkedin.jmx
LINKEDIN_USERS=10
LINKEDIN_DURATION=30
LINKEDIN_RAMPUP=
LINKEDIN_LOOPS=5
LINKEDIN_ENV=PERF

############################################
# GitHub
############################################

GITHUB_SCRIPT=Scripts/TestScripts/GitHub.jmx
GITHUB_USERS=10
GITHUB_DURATION=30
GITHUB_RAMPUP=3
GITHUB_LOOPS=5
GITHUB_ENV=PERF